In [17]:
import numpy as np

np.array(range(6))

array([0, 1, 2, 3, 4, 5])

In [18]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [19]:
np.logspace(0, 10, 100)

array([1.00000000e+00, 1.26185688e+00, 1.59228279e+00, 2.00923300e+00,
       2.53536449e+00, 3.19926714e+00, 4.03701726e+00, 5.09413801e+00,
       6.42807312e+00, 8.11130831e+00, 1.02353102e+01, 1.29154967e+01,
       1.62975083e+01, 2.05651231e+01, 2.59502421e+01, 3.27454916e+01,
       4.13201240e+01, 5.21400829e+01, 6.57933225e+01, 8.30217568e+01,
       1.04761575e+02, 1.32194115e+02, 1.66810054e+02, 2.10490414e+02,
       2.65608778e+02, 3.35160265e+02, 4.22924287e+02, 5.33669923e+02,
       6.73415066e+02, 8.49753436e+02, 1.07226722e+03, 1.35304777e+03,
       1.70735265e+03, 2.15443469e+03, 2.71858824e+03, 3.43046929e+03,
       4.32876128e+03, 5.46227722e+03, 6.89261210e+03, 8.69749003e+03,
       1.09749877e+04, 1.38488637e+04, 1.74752840e+04, 2.20513074e+04,
       2.78255940e+04, 3.51119173e+04, 4.43062146e+04, 5.59081018e+04,
       7.05480231e+04, 8.90215085e+04, 1.12332403e+05, 1.41747416e+05,
       1.78864953e+05, 2.25701972e+05, 2.84803587e+05, 3.59381366e+05,
      

In [20]:
y = np.arange(12)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [21]:
y.reshape(6, -1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [31]:
y.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
y.reshape(6,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [34]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
z = y.reshape(6, 2)
print(z)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [37]:
z.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
z

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [2]:
import numpy as np

In [3]:
np.random.seed(100)

In [1]:
import numpy as np
from sklearn import linear_model

regr = linear_model.LinearRegression()

x = [[164],[179],[162],[170]]
y=[53, 63, 55, 59]

regr.fit(x,y)

LinearRegression()